const PostData = [
  {
    id: 1001,
    name: 'kartik devarde',
    location: 'pune, maharashtra',
    like: 123,
    comments: 23,
    save: 21,
  },
  {
    id: 1002,
    name: 'john doe',
    location: 'new york, usa',
    like: 87,
    comments: 15,
    save: 10,
  },
  {
    id: 1003,
    name: 'alice smith',
    location: 'london, uk',
    like: 45,
    comments: 8,
    save: 5,
  },
  {
    id: 1004,
    name: 'raj patel',
    location: 'mumbai, maharashtra',
    like: 56,
    comments: 12,
    save: 9,
  },
  {
    id: 1005,
    name: 'sara jones',
    location: 'sydney, australia',
    like: 98,
    comments: 20,
    save: 15,
  },
  {
    id: 1006,
    name: 'juan rodriguez',
    location: 'mexico city, mexico',
    like: 34,
    comments: 7,
    save: 3,
  },
  {
    id: 1007,
    name: 'emily wang',
    location: 'beijing, china',
    like: 65,
    comments: 14,
    save: 11,
  },
  {
    id: 1008,
    name: 'mohammed al-farsi',
    location: 'riyadh, saudi arabia',
    like: 76,
    comments: 18,
    save: 13,
  },
  {
    id: 1009,
    name: 'lucas silva',
    location: 'rio de janeiro, brazil',
    like: 53,
    comments: 11,
    save: 8,
  },
  {
    id: 1010,
    name: 'anushka khanna',
    location: 'delhi, india',
    like: 112,
    comments: 25,
    save: 19,
  },
];

export default PostData;
// Now PostData contains 10 objects with 4-digit IDs
